### ISSUE TITLE
Unable to delineate the catchment

### ISSUE THREAD

**Issue by bhanu-IITD** [mdbartos/pysheds#106]
Hi, 
I am trying to delineate a catchment for Brahmaputra river using MERIT-DEM by following the exact steps mentioned in [quickstart.ipynb](https://github.com/mdbartos/pysheds/blob/master/examples/quickstart.ipynb) example.
However, I am unable to generate a catchment and the output is containing only a few pixels. Please have a look at the jupyter notebook attached and, as you can verify from google maps screenshot, the pour point also lies on the river.
Any help would be appreciated.
Thanks.
[Notebook link](https://github.com/bhanu-IITD/pysheds/blob/master/bputra_meritdem_basin.ipynb)
[Pour Point](https://github.com/bhanu-IITD/pysheds/blob/master/pour_point.jpg)

**Comment by mdbartos** [comment]
Greetings,

Have you tried using `grid.snap_to_mask` to ensure that the pour point lies on a cell with high accumulation?

See:
https://github.com/mdbartos/pysheds/blob/master/examples/snap_to_mask.ipynb

Thanks,
MDB

**Comment by bhanu-IITD** [comment]
I tried `grid.snap_to_mask` and it worked.
Thank you, Matt.

**Comment by bhanu-IITD** [comment]
Hi Matt,
The catchment delineated is having a smaller area than expected. It should extend more on the left in China's territory. Can you please help which parameter shall I tweak to have a larger area? Please see the screenshots having expected and delineated catchments.
Thanks and Regards.
Bhanu
![image](https://user-images.githubusercontent.com/60338532/78231334-4497e600-74f0-11ea-8ccb-f4db170ff47e.png)
![image](https://user-images.githubusercontent.com/60338532/78231420-64c7a500-74f0-11ea-982f-48835d4eecf6.png)

**Comment by mdbartos** [comment]
Greetings,

It's difficult for me to say, because I'm not exactly sure what the result should look like. Is this library yielding different results compared to e.g. QGIS or ArcGIS? Looking at Google Earth, I can't find where the Western Chinese portion connects with the Indian portion. Does that map you showed include subterranean flow?

The main parameter you have to work with is the pour point location*. If you think the basin should be bigger, try moving the pour point further downstream.

I'd recommend looking at the accumulation for the entire DEM so that you can visualize where all the subbasins are, and get a better idea of where to place the pour point.

Thanks,
MDB

* You could also try changing the routing algorithm from d8 to d-infinity, but this will make things a lot slower, and I don't think it will solve your problem.

**Comment by bhanu-IITD** [comment]
I've been able to achieve considerably good results by tweaking pour point location and `grid.snap_to_mask`.
