### ISSUE TITLE
Import errors 

### ISSUE THREAD

**Issue by msaharia** [mdbartos/pysheds#22]
On a fresh installation of `pysheds`, I get import errors for geojson, affine, and pyproj.

Might trip new users. The installation of dependencies could be automated using `setuptools`

**Comment by mdbartos** [comment]
Yes, that's a good idea.

Did you install using setup.py?

**Comment by msaharia** [comment]
No. I installed using pip.

________________________________

**Comment by gopalam** [comment]
Hi, I have a similar issue with errors from pysheds install (on  windows +anaconda + python3). The error is with lack of geojson. Trying to install geojson throws up another error- "environment is inconsistent" ... "caused by pysheds==0.2.7".  I was wondering what the workaround to this would be for this.  Thanks so much. GM

**Comment by mdbartos** [comment]
This should be resolved in the current version. Please reopen an issue if the problem persists.
