### ISSUE TITLE
quickstart notebook not reproducing same output

### ISSUE THREAD

**Issue by rosskush** [mdbartos/pysheds#24]
Hello, just wanted to say I think pysheds is a great project and I'm looking forward to seeing what else comes from it. 

So my issue is that I am simply trying to run the quickstart notebook and when I get to the "Delineate catchment" portion I am not producing the same output. I suspect it's something to do with the pour point but I am not sure. 

This is my output.

![image](https://user-images.githubusercontent.com/30669053/45248191-9e640a00-b2d3-11e8-983e-ae9f4e90f43a.png)

I know this is not a very informative question but I did not change anything from the quickstart notebook so I do not have much to add. 

Thanks, and let me know if you want more detail.

**Comment by mdbartos** [comment]
Hi Ross,

Thanks for letting me know. Yes, this looks like an issue with providing the correct pour point. Usually this happens when the pour point does not intersect a cell with a large flow accumulation (it's probably slightly off).

A couple questions:

1) Did you run all the cells in the notebook in order? Note that I load the source flow direction file from HydroSHEDS in cell 8. The flow directions produced from the flow direction algorithm in pysheds may be slightly different than those in the USGS flow direction dataset, meaning the provided pour point may no longer be on a cell with high flow accumulation.

2) Do you have the latest version of pysheds from the github repo?

Thanks,
MDB

**Comment by rosskush** [comment]
Matt, Yes I do have the current install of pysheds
pysheds                   0.2                       <pip>

I did notice I had an older install of pysheds in my conda env too, but I took care of that. 

When I use the hydrosheds flow direction raster, it works out. So I guess it is that the pour point is not close enough to a high flow accumulation cell.  

But if they both come from the same starting dem, wouldn't the flow accumulations be similar enough between hydrosheds and pysheds that the same pour point should be close?

Thanks,

**Comment by mdbartos** [comment]
There are a couple details that can affect the transition from DEM to flow directions:

- The geospatial projection can slightly alter computed flow directions: https://github.com/mdbartos/pysheds/blob/master/examples/flowdir_vs_projection.ipynb
- There are often situations where multiple possible flow directions are defined for a cell (e.g. there are two or more downstream cells at the same elevation difference). Different sources seem to have different methods for resolving this issue.

Unfortunately, I was not able to find documentation on which projections HydroSHEDS used, or how they dealt with multiple flow directions.

If you want to use the computed flow direction raster, you can shift your pour point to the nearest high-accumulation cell using `grid.snap_to_mask`.

Something like:
```python
xy_points = np.asarray([[-97.294167, 32.73750]])
grid.snap_to_mask(grid.view('acc') > 1000, xy_points)
```

Thanks,
MDB
