### ISSUE TITLE
Clarification: flow distance units

### ISSUE THREAD

**Issue by cfandel** [mdbartos/pysheds#71]
Hi, 

Some questions about the flow_distance function. 
This calculates the number of cells on the flow path from each cell in a subcatchment to the outlet of that subcatchment correct? So would multiplying a flow distance in cells by the pixel width in meters of my raster cells give a fair approximation of the flow distance in meters? Is this what specifying the weights does?

Also, in the example you give, flow_distance takes grid.catch as its input, but in the doc string it says it wants grid.dir. Which is correct?

I'm eventually planning on using this to calculate subcatchment "width" in SWMM.

Thanks!

PS: These tools are super useful thank you!

**Comment by mdbartos** [comment]
Hi @cfandel,

Thanks for your question. You can use the `weights` parameter to specify the distances from each cell to its downstream neighbor (this should account for differences in height, width, and diagonal distance). To get these distances, you can use `grid.cell_distances`. If you use the `as_crs` argument you will get the result in projected units (e.g. meters). So, you can do something like:

```python
import pyroj

# Projection for the location I'm interested in (Texas for the example DEM)
new_crs = pyproj.Proj('+init=epsg:3083')

cell_distances = grid.cell_distances('catch', as_crs=new_crs, inplace=False)
flow_distances = grid.flow_distance(x=x, y=y, data='catch', weights=cell_distances.ravel(), inplace=False)
```
(Note that I haven't tested the above code sample)

I believe you can use either `dir` or `catch`, as long as it's a flow direction raster. The flow distance function makes you input a pour point, so the result should be the same either way (any points that aren't upstream of the pour point will have a flow distance of infinity).

Btw, I made some scripts to convert DEMs to SWMM input files for a paper a little while back. The source code is here (however, it's really messy because I didn't really intend to distribute it): https://github.com/kLabUM/hydraulic-controller-placement/blob/development/notebooks/swmm.py

Glad that this library has been helpful for you :)

Thanks,
MDB

**Comment by mdbartos** [comment]
For reference, the weights for `grid.flow_distance` are used as edge weights in a directed graph of the watershed. Shortest paths to the outlet are then determined using something like Djikstra's algorithm (scipy chooses the algorithm depending on what's best for the particular situation).

**Comment by cfandel** [comment]
Super helpful thanks! This approach worked great for me using the flow direction raster (though not the catchment raster when it came to calculating cell distances). 
Also, I think your SWMM input file code will be helpful as well - I've written something similar, but it's useful to see another approach to it!

**Comment by mdbartos** [comment]
Looks cool!

Btw, what happened when you tried to use cell_distances on the catchment raster? Did it raise an error?

**Comment by cfandel** [comment]
Actually it's weird because initially when I tried it just gave me an array of zeros, but I just tested it again and now it works fine with either one...not sure what I was doing at first that gave different results.
