### ISSUE TITLE
Recursive function d8_catchment_search causes Python to crash

### ISSUE THREAD

**Issue by DominiqueBrunet** [mdbartos/pysheds#81]
Hi,

For larger DEM, the catchment method will crash Python. The cause seems to be a out-of-memory problem in the recursive function d8_catchment_search. Setting the recursion limit higher will not help and setting the recursion limit lower might avoid a hard crash, but might give a wrong (incomplete) catchment basin.

The solution would be to refactor the function from recursive to iterative. @mdbartos, I could submit an example of code when it crashes and a pull request that fixes the problem if you would guide me through the process.

**Comment by mdbartos** [comment]
Greetings,

It's been several years since I wrote the original implementation, so I think refactoring would certainly be a good idea. Namely, the current implementation uses a list to store visited cells, which may not be ideal memory-wise. It would probably be better to just use a boolean array. I'm not sure if getting rid of the recursion would necessarily help with memory consumption.

What size DEM are you using?

**Comment by DominiqueBrunet** [comment]
The original DEM I am using is about 17000x18000 pixels, but the bug occurs even when I crop it to about 1500x1200.

Getting rid of recursion worked for me without memory problem.

**Comment by mdbartos** [comment]
Greetings,

I'll take a look at this issue soon. It shouldn't be crashing on a DEM of that size though. See this example for instance (5000 x 5000): https://github.com/mdbartos/pysheds/blob/master/examples/no_metadata.ipynb

It may be that you are calling the function on the original data source rather than the clipped 'view' of the data.

**Comment by DominiqueBrunet** [comment]
The clipped DEM for six different larger watersheds lead to a crash, but other smaller ones worked fine, so I don't think it has to do on how I clipped the data.

I can try to extract and package the data and code that generated the error if you want. How would you like the data?

**Comment by mdbartos** [comment]
Greetings, this should be fixed in v0.3, as the python catchment function has been reimplemented in numba. Please reopen if the issue persists.
